export const users = [
  {
    "first name": "Lucrèce",
    name: "Cattermoul",
    email: "gcattermoul0@yolasite.com",
    url: "https://xsgames.co/randomusers/avatar.php?g=female",
    gender: "M",
    age: 1,
    interest: ["Gaming", "Dancing & Singing", "Language"],
    bio: "bio of the user",
    company: "Google",
    role: "Software Tester",
    techStack: ["Java", "PHP", "Javascript"],
  },
  {
    "first name": "Célestine",
    name: "Sedgemond",
    email: "csedgemond1@slate.com",
    url: "https://xsgames.co/randomusers/avatar.php?g=male",
    gender: "M",
    age: 2,
  },
  {
    "first name": "Maïwenn",
    name: "Edie",
    email: "nedie2@privacy.gov.au",
    url: "https://picsum.photos/200",

    gender: "F",
    age: 3,
  },
  {
    "first name": "Laurélie",
    name: "Dysert",
    email: "tdysert3@constantcontact.com",
    url: "https://picsum.photos/201",
    gender: "M",
    age: 4,
  },
  {
    "first name": "Salomé",
    name: "Marquand",
    email: "lmarquand4@samsung.com",
    url: "https://picsum.photos/202",
    gender: "M",
    age: 5,
  },
  {
    "first name": "Marie-ève",
    name: "McCumskay",
    email: "tmccumskay5@ebay.co.uk",
    url: "https://picsum.photos/203",
    gender: "F",
    age: 6,
  },
  {
    "first name": "Kù",
    name: "Larmouth",
    email: "klarmouth6@nytimes.com",
    url: "https://picsum.photos/204",
    gender: "F",
    age: 7,
  },
  {
    "first name": "Gwenaëlle",
    name: "Jervis",
    email: "fjervis7@yahoo.co.jp",
    url: "https://picsum.photos/205",
    gender: "M",
    age: 8,
  },
  {
    "first name": "Mén",
    name: "Darkin",
    email: "ndarkin8@ocn.ne.jp",
    url: "https://picsum.photos/206",
    gender: "M",
    age: 9,
  },
  {
    "first name": "Léa",
    name: "Surgeon",
    email: "rsurgeon9@biblegateway.com",
    url: "https://picsum.photos/207",
    gender: "F",
    age: 10,
  },
  {
    "first name": "Nuó",
    name: "MacNucator",
    email: "emacnucatora@mail.ru",
    url: "https://picsum.photos/208",
    gender: "F",
    age: 11,
  },
  {
    "first name": "Léone",
    name: "Lowndesbrough",
    email: "llowndesbroughb@skype.com",
    url: "https://picsum.photos/209",
    gender: "M",
    age: 12,
  },
  {
    "first name": "Cloé",
    name: "Kyme",
    email: "ekymec@feedburner.com",
    url: "https://picsum.photos/210",
    gender: "M",
    age: 13,
  },
  {
    "first name": "Kévina",
    name: "Francombe",
    email: "nfrancombed@rediff.com",
    url: "https://picsum.photos/211",

    gender: "M",
    age: 14,
  },
  {
    "first name": "Eliès",
    name: "Whenman",
    email: "kwhenmane@networksolutions.com",
    url: "https://picsum.photos/212",
    gender: "F",
    age: 15,
  },
  {
    "first name": "Mélinda",
    name: "Denisyuk",
    email: "ndenisyukf@kickstarter.com",
    url: "https://picsum.photos/213",
    gender: "F",
    age: 16,
  },
  {
    "first name": "Daphnée",
    name: "Pear",
    email: "mpearg@eepurl.com",
    url: "https://picsum.photos/214",
    gender: "M",
    age: 17,
  },
  {
    "first name": "Måns",
    name: "Sooper",
    email: "msooperh@sfgate.com",
    url: "https://picsum.photos/215",
    gender: "F",
    age: 18,
  },
  {
    "first name": "Aí",
    name: "Venton",
    email: "lventoni@infoseek.co.jp",
    url: "https://picsum.photos/216",
    gender: "M",
    age: 19,
  },
  {
    "first name": "Annotés",
    name: "Manuely",
    email: "nmanuelyj@hatena.ne.jp",
    url: "https://picsum.photos/217",
    gender: "M",
    age: 20,
  },
];

export const mages = [
  {
    image: "https://picsum.photos/218",
  },
  {
    image: "https://picsum.photos/219",
  },
  {
    image: "https://picsum.photos/220",
  },
  {
    image: "https://picsum.photos/221",
  },
  {
    image: "https://picsum.photos/222",
  },
];
